### PR TITLE
Native table row button revision

### PR DESCRIPTION
**Pull request by lisavo7**

### CODE REVIEW

**Review by jzoo — APPROVED** [review]
looks good

**Review by debra-lonsdorf — DISMISSED** [review]

**Review by charlietriplett — CHANGES_REQUESTED** [review]
Is the ### Announcement examples section is empty intentionally?

If the intent is to delete that, let's clean out the heading as well.

**Comment by lisavo7** [comment]
> Is the ### Announcement examples section is empty intentionally?
> 
> If the intent is to delete that, let's clean out the heading as well.

@charlietriplett We will be populating these sections in the next MR that will be generated this week

**Comment by charlietriplett** [comment]
> 

Let's not leave "coming soon" content sections in the entry — When you have the _content_, **then** let's then add the headings.

**Comment by lisavo7** [comment]
> > 
> 
> Let's not leave "coming soon" content sections in the entry — When you have the _content_, **then** let's then add the headings.

Fixed

**Review by max-jin — APPROVED** [review]

**Pull request merged**
